services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: dacongcu-backend
    ports:
      - "8081:8080"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: dacongcu-frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge