spring.datasource.url=${APP_MYSQL_URL:jdbc:mysql://localhost:3306/dataset?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${APP_MYSQL_USERNAME:manhsd0}
spring.datasource.password=${APP_MYSQL_PASSWORD:28052004}

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
